language: c

env:
  - CFLAGS=c89
  - CFLAGS=c99
  - CFLAGS=c11

compiler:
  - gcc

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data

before_script:
  - cmake --version

script:
  - mkdir cibuild
  - cd cibuild
  - cmake .. && make -verbose=1 -j
