language: c

env:
  - CFLAGS="-std=c89"
  - CFLAGS="-std=c99"
  - CFLAGS="-std=c11"

compiler:
  - clang

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data

before_script:
  - cmake --version

script:
  - mkdir cibuild
  - cd cibuild
  - cmake .. && make -j
