language: c

env:
  - STD=c89
  - STD=c99
  - STD=c11

compiler:
  - gcc

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data

before_script:
  - cmake --version

script:
  - mkdir cibuild
  - cd cibuild
  - CFLAGS="-std=$STD" cmake .. && make -j
